# Generated by Django 3.1.7 on 2021-03-03 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.UUIDField(default=uuid.UUID('23422fe0-5fe7-45f3-9c9d-1c9d8fa6a15c'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('primary_color', models.CharField(default='#cccccc', max_length=7)),
                ('secondary_color', models.CharField(default='#999999', max_length=7)),
                ('background_color', models.CharField(default='#444444', max_length=7)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-create_date', 'title'],
            },
        ),
    ]
