# Generated by Django 3.1.7 on 2021-03-03 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.UUIDField(default=uuid.UUID('e312790e-b050-4fd6-b2bb-da7165d968ed'), primary_key=True, serialize=False),
        ),
    ]
