# Generated by Django 3.1.7 on 2021-03-03 05:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Question', '0002_auto_20210303_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('choice_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='Question.question')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
