# Generated by Django 3.1.7 on 2021-03-03 05:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quiz', '0002_auto_20210303_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.UUID('73c8b37c-ccd2-4563-ad14-87005ee80470'), primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=128)),
                ('order', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Quiz.quiz')),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
    ]
