# Generated by Django 3.1.7 on 2021-03-03 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.UUIDField(default=uuid.UUID('45450fad-f528-4d8b-a6ea-62f7065b262b'), primary_key=True, serialize=False),
        ),
    ]
